INTERNAL_ERROR = "Internal Sever Error"
INTERNAL_ERROR_UPDATE = "Something went wrong while updating the data."
INTERNAL_ERROR_PLACE_ORDER = "Something went wrong while placing order."
INTERNAL_ERROR_CANCEL_ORDER = "Something went wrong while cancelling the order."
INTERNAL_ERROR_FETCH_ORDER = "Something went wrong while fetching the orders."
NOT_FOUND = "Not Found"
NOT_FOUND_PRODUCT = "No product available ."
NOT_FOUND_ORDER = "No orders available."
NOT_FOUND_USER = "This user does not exist."
CONFLICT = "Conflict"
PRODUCT_ID_EXIST = "This id already exists"
INTERNAL_ERROR_ADD_PRODUCT = "Something went wrong while inserting data."
INTERNAL_ERROR_DELETE = "Something went wrong while deleting the data."
INTERNAL_ERROR_FETCH = "Something went wrong while fetching the data."
INTERNAL_ERROR_FETCH_PRODUCT = "Something went wrong while retrieving the products."
UNPROCESSABLE_ENTITY = "Unprocessable entity"
VALID_PARAM_MESSAGE = "Enter valid query parameter"
NOT_FOUND_PRODUCT_KEYWORD = "No product available with this keyword."
SUCCESS = "Success"
FORBIDDEN = "Forbidden"
NOT_ALLOWED = "You are not allowed to access this functionality."
USERNAME_TAKEN = "Enter another username as this username is taken."
USERNAME = 'username'
PASSWORD = 'password'
PHONE = 'phone'
ADDRESS = 'address'
ADMIN = 'Admin'
DISTINCT = 'distinct'
ALL = 'all'
ONE = '1'
MINUS_ONE = '-1'
ZERO = '0'
CUSTOMER = 'Customer'
SELLER = 'Seller'

